# Generated by Django 2.2.2 on 2019-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewdownvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewupvotes',
            field=models.IntegerField(default=0),
        ),
    ]
