# Generated by Django 2.2.2 on 2019-06-06 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewsong',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='reviews.Song'),
        ),
        migrations.AddField(
            model_name='song',
            name='ratingcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='songrating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
