# Generated by Django 2.2.2 on 2019-06-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190606_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songrating',
            field=models.IntegerField(default=0),
        ),
    ]
